### ISSUE TITLE
'enterRNGScope' not provided by package 'Rcpp

### ISSUE THREAD

**Issue by loverend** [immunogenomics/LISI#3]
Hi,

I have been trying to run LISI but whenever I try to run just the basic function described on the github:

```r
lisi_res <- lisi::compute_lisi(lisi::X, lisi::meta_data, c('label1', 'label2'))
```

I get the following error:

```
Error in compute_simpson_index(t(dknn$nn.dists), t(dknn$nn.idx) - 1, labels,  : 
  function 'enterRNGScope' not provided by package 'Rcpp'
```

I have seen some posts suggesting updating the namespace / description which I have done but it hasn't got it running. 
Any suggestions much appreciated. 

Best wishes 
Lauren

**Comment by slowkow** [comment]
Thanks for reporting this! I noticed that the same issue was reported here:

https://github.com/theislab/scib/issues/33

I hope that the commit mentioned above fixes the issue for everyone.

**Comment by MichaelChirico** [comment]
For anyone else encountering this in a different context, it seems the issue is calling Rcpp code _without_ loading Rcpp.

The minimal solution is to add `loadNamespace("Rcpp")` to your package's `.onLoad()` hook.

The more typical solution is to add `import(Rcpp)` or `importFrom(Rcpp, evalCpp)` to your `NAMESPACE` (or, for roxygen2 users, `#' import(Rcpp)` / `#' @importFrom Rcpp evalCpp`).

This is what's done by `Rcpp::Rcpp.package.skeleton()`:

https://github.com/RcppCore/Rcpp/blob/97ae61797528b16d6d672c1cf2c2b1f1eaeef8f0/R/Rcpp.package.skeleton.R#L111-L117

PS A maximal solution is to add `Rcpp` to your package's `Depends:` (which will ensure Rcpp is always _attached_ before your package is loaded). I strongly recommend against using `Depends:` for R packages, but personally originally encountered this issue when migrating a package from `Depends: Rcpp` to `Imports: Rcpp`.
